CREATE DATABASE SERVICECLIENT;

USE SERVICECLIENT;

CREATE TABLE CLIENT(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PHONE VARCHAR(11) NOT NULL,
	ADRESS VARCHAR(100) NOT NULL
);

INSERT INTO CLIENT VALUES (NULL, 'GABRIEL FRANCISCO', '51998673148', 'AV OTTO NEYEMEIER, 884');