
/*MYSQL TABLE CONTENT... JUST FOR REMINDING PURPOSES*/
 
USE SERVICECLIENT;

CREATE TABLE SERVICE(
	IDSERVICE INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    SERVICEDESC LONGTEXT NOT NULL,
    ID_CLIENT INT,
    CLIENTNAME VARCHAR(50)  NOT NULL,
    foreign key(ID_CLIENT)
    references CLIENT(ID)
);
